PRINT MACRO TEMP
  LEA DX,TEMP
  MOV AH,09H
  INT 21H
ENDM

DATA SEGMENT
 M1 DB 0AH,0DH,'1. CREATE   2. DELETE  3. EXIT$'
 M2 DB 0AH,0DH,'ENTER YOUR CHOICE : $'
 M3 DB 0AH,0DH,'ENTER FILE TO CREAT : $'
 M4 DB 0AH,0DH,'ENTER FILE TO DELETE : $'
 M5 DB 0AH,0DH,'FILE HAS BEEN CREAETED...$'
 M6 DB 0AH,0DH,'FILE HAS BEEN DELETED...$'
 M7 DB 0AH,0DH,'ERROR : INVALID OPERATION....$'
 STR DB 50
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE,DS:DATA

START:MOV AX,DATA
      MOV DS,AX
MENU: MOV AX,0003H
      MOV BX,0F00H
      MOV DX,0000H
      INT 10H
      MOV AX,0200H
      MOV BX,0000H
      MOV DX,0000H
      INT 10H
      PRINT M1
      PRINT M2
      MOV AH,01H
      INT 21H
      CMP AL,'1'
      JE CREATE
      CMP AL,'2'
      JE DELETE
      CMP AL,'3'
      JMP STOP
      JMP ERROR
STOP: MOV AH,4CH
      INT 21H
CREATE:PRINT M3
       CALL READ
       LEA DX,STR
       MOV AH,3CH
       MOV CX,0000H
       INT 21H
       JC ERROR
       PRINT M5
       MOV AH,08H
       INT 21H
       JMP MENU
ERROR: PRINT M7
       MOV AH,08H
       INT 21H
       JMP MENU
DELETE: PRINT M4
        CALL READ
        LEA DX,STR
        MOV AH,41H
        INT 21H
        JC ERROR
        PRINT M6
        MOV AH,08H
        INT 21H
        JMP MENU
READ PROC
       LEA SI,STR
NEXT:  MOV AH,01H
       INT 21H
       CMP AL,0DH
       JE BACK
       MOV [SI],AL
       INC SI
       JMP NEXT
BACK:  RET
READ ENDP
       CODE ENDS
       END START

